### ISSUE TITLE
Deprecated packages upgrade

### ISSUE THREAD

**Issue by erikakus** [kontent-ai/sample-app-net#139]
### Motivation

Solution is not buildable when trying to upgrade deprecated package "Kentico.AspNetCore.LocalizedRouting" to "AspNetCore.Mvc.Routing.Localization"

### Proposed solution

I see there is already work in progress in branches, however I wanted to ask about plans and timeline for releasing updates.

**Comment by Simply007** [comment]
Hello @erikakus,

We are migrating the repositories to the new [kontent-ai GitHub organization](https://github.com/kontent-ai). As a part of that, we are polishing the samples as well. 

I have already tested to accommodate the replacement package, but I found an issue in the taghelper (fixed locally in https://github.com/Kentico/kontent-sample-app-net/commit/c33ea6cd4d368d5f4337942c24704f86d583fffa).

The current decision is whether we want to use the package or showcase the standard way of making localization: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-6.0

From my point of view, it is not a good practice a to use community-based package, that is not really being maintained, so we probably end up with the second solution, but I don't have an ETA for that, because we need to define the behavior before we implement it.

I would be interested in getting your point on things. I believe one of our CSMs reach out to you and scheduled a call about that.
